#!/bin/bash
# log-run.sh - Log agent run to file

set -e

# Get parameters
AGENT_NAME=$1
STATUS=$2
shift 2
NOTES="$@"

# Create logs directory if needed
mkdir -p .ai/logs/runs

# Generate timestamp
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
LOG_FILE=".ai/logs/runs/${AGENT_NAME}-${TIMESTAMP}.md"

# Create log entry
cat > "$LOG_FILE" << EOF
# Run Log: $AGENT_NAME

**Date**: $(date -Iseconds)
**Agent**: $AGENT_NAME
**Status**: $STATUS

## Notes

$NOTES

## Context

- Working Directory: $(pwd)
- Git Branch: $(git branch --show-current 2>/dev/null || echo "N/A")
- Git Commit: $(git rev-parse --short HEAD 2>/dev/null || echo "N/A")

## Files Changed

\`\`\`bash
$(git diff --name-only 2>/dev/null || echo "N/A")
\`\`\`

---

*Auto-generated by log-run.sh*
EOF

echo "Log saved to: $LOG_FILE"
